name: Build and Deploy Java Web App to Azure CICD Training

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:

env:
  JAVA_VERSION: '11'  


jobs:
  jobbuild:
    name: AWS Build and Deploy
    runs-on: ubuntu-latest
# Adding JDK to the Worker
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: Build with Maven
      run: mvn package --file pom.xml

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v13
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: petclinic
        environment_name: Petclinic-env-1
        version_label: ${{github.SHA}}
        region: us-east-2
        deployment_package: target/spring-petclinic-2.4.2.jar